In [3]:
import pandas as pd

# Load dataset
df = pd.read_csv("../data/coaching_student_data.csv")

df.head()

        Name  English  Hindi  Maths  Science  Social Science  Computer
0     Saurya       51     60     50       64              55        71
1      Advik       80     90     66       74              91        68
2    Tanishi       75     82     74       81              84        90
3   Jaishree       75     64     90       75              84        60
4  Vaishnavi       84     72     84       86              49        84

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            14 non-null     str
 1   English         14 non-null     int64
 2   Hindi           14 non-null     int64
 3   Maths           14 non-null     int64
 4   Science         14 non-null     int64
 5   Social Science  14 non-null     int64
 6   Computer        14 non-null     int64
dtypes: int64(6), str(1)
memory usage: 916.0 bytes

In [ ]:
#Clean column names

df.columns = df.columns.str.strip()

In [ ]:
#Total Marks of students
df["Total"]=df.iloc[:,1:7].sum(axis=1)

In [14]:
#Percentage of students

df["Percentage"] = (df["Total"] / 600)*100

In [15]:
#Add Grade

def assign_grade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 75:
        return "A"
    elif percentage >= 60:
        return "B"
    elif percentage >= 50:
        return "C"
    elif percentage >= 40:
        return "D"
    else:
        return "Fail"

df["Grade"] = df["Percentage"].apply(assign_grade)

In [16]:
#Saved cleaned dataset

df.to_csv("../data/coaching_student_cleaned.csv", index=False)

In [18]:
#Top Students
top_students = df.sort_values(by="Percentage", ascending=False).head(5)

top_students[["Name", "Percentage"]]

      Name  Percentage
13   Vivek   92.500000
12  Ritesh   92.500000
5    Aavya   88.500000
6   Shruti   87.166667
10   Tanvi   83.000000